emotions=["amusement",
          "anger",
          "attachment love",
          "awe","craving",
          "disgust",
          "excitment",
          "fear",
          "joy",
          "neutral",
          "nurturant love",
          "sadness",
          "positive valence",
          "negative valence",
          "arousing",
          "calming",
          "motivated to approach",
          "motivated to avoid"]
