emotions=["amusement",
          "anger",
          "attachment love",
          "awe","craving",
          "disgust",
          "excitement",
          "fear",
          "joy",
          "neutral",
          "nurturant love",
          "sadness",
          "positive valence",
          "negative valence",
          "arousing",
          "calming",
          "motivated to approach",
          "motivated to avoid"]

prompts = [
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much amusement the picture would elicit in an average person on a scale from 1-9. Amusement: An emotional experience associated with opportunities for humor and events that violate expectations. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much anger the picture would elicit in an average person on a scale from 1-9. Anger: An emotional experience characterized by antagonism toward someone or something perceived as deliberately harmful or unfair. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much attachment love the picture would elicit in an average person on a scale from 1-9. Attachment love: An emotional experience tied to opportunities for affiliation, interdependence, and intimacy. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much awe the picture would elicit in an average person on a scale from 1-9. Awe: An emotional experience triggered by stimuli that are vast and beyond the ordinary frame of reference, often involving wonder, admiration, and a sense of being small in the presence of something greater than oneself. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much craving the picture would elicit in an average person on a scale from 1-9. Craving: An emotional experience associated with specific sensory pleasure that aids in distinguishing nutritional foods from nutritionally neutral objects and toxins. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much disgust the picture would elicit in an average person on a scale from 1-9. Disgust: An emotional experience involving strong aversion or repulsion toward something perceived as offensive, contaminating, or unpleasant. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much excitement the picture would elicit in an average person on a scale from 1-9. Excitement: A high-intensity emotional experience in response to novelty, challenge, or human excellence, often associated with some degree of risk. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much fear the picture would elicit in an average person on a scale from 1-9. Fear: An emotional experience triggered by a perceived threat or danger. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much joy the picture would elicit in an average person on a scale from 1-9. Joy: An emotional state marked by the absence of strong emotions, either positive or negative, characterized by calmness and balance without significant arousal. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how neutral the picture is for an average person on a scale from 1-9. Neutral: An emotional state marked by the absence of strong emotions, either positive or negative, characterized by calmness and balance without significant arousal. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much nurturant love the picture would elicit in an average person on a scale from 1-9. Nurturant love: An emotional experience linked to the adaptive opportunities provided by offspring or other vulnerable kin. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much sadness the picture would elicit in an average person on a scale from 1-9. Sadness: An emotional experience characterized by feelings of disappointment, grief, or hopelessness. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much positive valence the picture would elicit in an average person on a scale from 1-9. Positive valence: An emotional state characterized by feelings of pleasure, satisfaction, or well-being, often associated with favorable outcomes or circumstances. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much negative valence the picture would elicit in an average person on a scale from 1-9. Negative valence: An emotional state characterized by feelings of discomfort, displeasure, or distress, often associated with unfavorable outcomes or situations. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how arousing the picture is to an average person on a scale from 1-9. Arousing: An emotional state characterized by heightened physiological and psychological activity, such as increased heart rate, energy, or alertness. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how calming the picture is to an average person on a scale from 1-9. Calming: An emotional state marked by a sense of tranquility and composure, with low levels of emotional arousal or agitation. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how motivating the picture is to approach, on a scale from 1-9. Motivated to Approach: An emotional drive that compels an individual to move toward a desired goal, object, or situation, often associated with curiosity, attraction, or reward. Don't use fixed parameters, be precise, not quick. Write only a number.""",
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how motivating the picture is to avoid, on a scale from 1-9. Motivated to Avoid: An emotional drive that compels an individual to move away from an undesired or threatening goal, object, or situation, often associated with fear, discomfort, or aversion. Don't use fixed parameters, be precise, not quick. Write only a number."""
]


