emotions=["amusement",
          "anger",
          "attachment love",
          "awe","craving",
          "disgust",
          "excitment",
          "fear",
          "joy",
          "neutral",
          "nurturant love",
          "sadness",
          "positive valence",
          "negative valence",
          "arousing",
          "calming",
          "motivated to approach",
          "motivated to avoid"]

prompts = [
    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much amusement the picture would elicit in an average person on a scale from 1-9. Amusement: An emotional experience associated with opportunities for humor and events that violate expectations. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick.""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much anger the picture would elicit in an average person on a scale from 1-9. Anger: An emotional experience characterized by antagonism toward someone or something perceived as deliberately harmful or unfair. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much attachment love the picture would elicit in an average person on a scale from 1-9. Attachment love: An emotional experience tied to opportunities for affiliation, interdependence, and intimacy.. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much awe the picture would elicit in an average person on a scale from 1-9. Awe: An emotional experience triggered by stimuli that are vast and beyond the ordinary frame of reference, often involving wonder, admiration, and a sense of being small in the presence of something greater than oneself. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much craving the picture would elicit in an average person on a scale from 1-9. Craving: An emotional experience associated with specific sensory pleasure that aids in distinguishing nutritional foods from nutritionally neutral objects and toxins. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much disgust the picture would elicit in an average person on a scale from 1-9. Disgust: An emotional experience involving strong aversion or repulsion toward something perceived as offensive, contaminating, or unpleasant. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much excitement the picture would elicit in an average person on a scale from 1-9. Excitement: A high-intensity emotional experience in response to novelty, challenge, or human excellence, often associated with some degree of risk. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much fear the picture would elicit in an average person on a scale from 1-9. Fear: An emotional experience triggered by a perceived threat or danger. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much joy the picture would elicit in an average person on a scale from 1-9. Joy: An emotional state marked by the absence of strong emotions, either positive or negative, characterized by calmness and balance without significant arousal. I want you to provide ratings with 2 decimal points. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how neutral the picture is for an average person on a scale from 1-9.  Neutral: An emotional state marked by the absence of strong emotions, either positive or negative, characterized by calmness and balance without significant arousal.  I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much nurturant love the picture would elicit in an average person on a scale from 1-9. Nurturant love: An emotional experience linked to the adaptive opportunities provided by offspring or other vulnerable kin. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much sadness the picture would elicit in an average person on a scale from 1-9. Sadness: An emotional experience characterized by feelings of disappointment, grief, or hopelessness. I want you to provide ratings with 2 decimal points. I would like you to rate each photo 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much positive valence the picture would elicit in an average person on a scale from 1-9. The positive valence is defined as an emotional state characterized by feelings of pleasure, satisfaction, or well-being, often associated with favorable outcomes or circumstances. I want you to provide ratings with 2 decimal points. I would like you to rate the photos 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how much negative valence the picture would elicit in an average person on a scale from 1-9. The negative valence is defined as an emotional state characterized by feelings of discomfort, displeasure, or distress, often associated with unfavorable outcomes or situations.. I want you to provide ratings with 2 decimal points. I would like you to rate the photos 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how arousing the picture is to an average person on a scale from 1-9. Arousing reflects an emotional state characterized by heightened physiological and psychological activity, such as increased heart rate, energy, or alertness. I want you to provide ratings with 2 decimal points. I would like you to rate the photos 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """hi, I'm affective scientist and I would like to rate some pictures. I'm interested in rating how calming the picture is to an average person on a scale from 1-9. Calming reflects An emotional state marked by a sense of tranquility and composure, with low levels of emotional arousal or agitation. I want you to provide ratings with 2 decimal points. I would like you to rate the photos 50 times and draw the average of the 50 ratings along with the standard deviation. Don't use fixed parameters, be precise, not quick""" + " Write only average and standard deviation after space.",

    """Hi, I'm an affective scientist, and I would like to rate some pictures. I'm interested in rating how motivating the picture is to approach, on a scale from 1–9. Motivated to Approach reflects an emotional drive that compels an individual to move toward a desired goal, object, or situation, often associated with curiosity, attraction, or reward. I want you to provide ratings with 2 decimal points. Please rate each photo 50 times, calculate the average of the 50 ratings, and report the standard deviation. Avoid using fixed parameters; instead, ensure precision in your ratings by thoroughly considering each image.""" + " Write only average and standard deviation after space.",

    """Hi, I'm an affective scientist, and I would like to rate some pictures. I'm interested in rating how motivating the picture is to avoid, on a scale from 1–9. Motivated to Avoid reflects an emotional drive that compels an individual to move away from an undesired or threatening goal, object, or situation, often associated with fear, discomfort, or aversion. I want you to provide ratings with 2 decimal points. Please rate each photo 50 times, calculate the average of the 50 ratings, and report the standard deviation. Avoid using fixed parameters; instead, ensure precision in your ratings by thoroughly considering each image.""" + " Write only average and standard deviation after space."
]
